### ISSUE TITLE
No module named 'ida_regfinder'

### ISSUE THREAD

**Issue by 0xObjc** [doronz88/swift_reversing#2]
```E:\IDA Pro 8.3\plugins\ida_script.py: No module named 'ida_regfinder'
Traceback (most recent call last):
  File "E:\IDA Pro 8.3\python\3\ida_idaapi.py", line 577, in IDAPython_ExecScript
    exec(code, g)
  File "E:/IDA Pro 8.3/plugins/swift_reversing.py", line 7, in <module>
    import ida_regfinder
ModuleNotFoundError: No module named 'ida_regfinder'
```

**Comment by doronz88** [comment]
Maybe its only for ida 8.4+?
